버그 수정 None 값에 대해서 곱하기 연산을 하다가 에러나는 경우가 있어서 연산이 일어나지 않도록 조건문 추가함 카페24(00260879) 로 확인 가능
Traceback (most recent call last):
  File "/tmp/test/fss.py", line 105, in execute
    fs = corp.extract_fs(bgn_de='20100101', separate=True, report_tp=['quarter'])
  File "/tmp/test/.env/lib/python3.9/site-packages/dart_fss/corp/corp.py", line 233, in extract_fs
    return extract(self.corp_code, bgn_de, end_de, fs_tp, separate, report_tp, lang, separator, dataset)
  File "/tmp/test/.env/lib/python3.9/site-packages/dart_fss/fs/extract.py", line 1325, in extract
    raise e
  File "/tmp/test/.env/lib/python3.9/site-packages/dart_fss/fs/extract.py", line 1296, in extract
    statements, label_df = merge_fs(statements, nstatements, fs_tp=fs_tp, label_df=label_df)
  File "/tmp/test/.env/lib/python3.9/site-packages/dart_fss/fs/extract.py", line 960, in merge_fs
    ndata, nlabels = compare_df_and_ndf_value(column, df, ndf, ndata, nlabels)
  File "/tmp/test/.env/lib/python3.9/site-packages/dart_fss/fs/extract.py", line 815, in compare_df_and_ndf_value
    nvalue = sign * ndf[column].iloc[index]
TypeError: ("unsupported operand type(s) for *: 'int' and 'NoneType'", "An error occurred while fetching or analyzing {'rcp_no': '20161114001928', 'corp_code': '00260879', 'corp_name': '카페24', 'stock_code': '042000', 'corp_cls': 'K', 'report_nm': '분기보고서 (2016.09)', 'flr_nm': '카페24', 'rcept_dt': '20161114', 'rm': ''}.")

(cherry picked from commit 84afef82afc9d6893518acc6e21e85fef88cdcc9)